### ISSUE TITLE
Update the GitHub Actions workflow file

### ISSUE THREAD

**Issue by damithc** [se-edu/duke#66]
See https://github.com/nus-cs2103-AY2122S1/forum/issues/211#issuecomment-915343182

**Comment by damithc** [comment]
full-template branch: gradle.yml is outdated as compared to AB3 equivalent.
In particular,
```
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx
```
